# Generated by Django 2.1.7 on 2019-03-18 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hottip.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', hottip.fields.JsonField(default={'day': 1, 'day_of_week': '*', 'hour': '*', 'minute': '*', 'month': '*'})),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SLACK', 'Slack'), ('WEBHOOK', 'Webhook')], max_length=200)),
                ('attribute', hottip.fields.JsonField(default={})),
                ('tips_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hottip.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('enable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', related_query_name='tip', to='hottip.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='distributedlog',
            name='tips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hottip.Tip'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name',)},
        ),
    ]
