# Generated by Django 2.1.7 on 2019-03-03 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hottip', '0002_auto_20190302_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SLACK', 'Slack'), ('WEBHOOK', 'Webhook')], max_length=200)),
                ('attibute', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tip',
            name='enabled',
        ),
        migrations.AddField(
            model_name='assignment',
            name='power',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='channel',
            name='tips',
            field=models.ManyToManyField(through='hottip.Assignment', to='hottip.Tip'),
        ),
        migrations.AddField(
            model_name='tip',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='level',
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('tip', 'channel')},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='frequency',
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='distributor',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hottip.Channel'),
        ),
    ]
