# Generated by Django 2.1.7 on 2019-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hottip', '0002_auto_20190318_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
