# Generated by Django 2.1.7 on 2019-03-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hottip', '0003_auto_20190303_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotifiedHistory',
            new_name='DistributedLog',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='attibute',
            new_name='attribute',
        ),
        migrations.AddField(
            model_name='distributor',
            name='tips_count',
            field=models.IntegerField(default=1),
        ),
    ]
