# Generated by Django 2.1.7 on 2019-03-17 11:39

from django.db import migrations
import hottip.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hottip', '0005_auto_20190312_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='attribute',
            field=hottip.fields.JsonField(default={}),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='schedule',
            field=hottip.fields.JsonField(default={'day': 1, 'day_of_week': '*', 'hour': '*', 'minute': '*', 'month': '*'}),
        ),
    ]
